$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train
version: 1
description: Trains the model
display_name: Train model
type: command
inputs:
  training_data:
    type: uri_file
code: .
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:26
command: >-
  python component.py --training-data ${{inputs.training_data}}