$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Prepare wachttijden dataset
description: Prepares the feature set for the wachttijden model
compute: azureml:cc-3v3j6znbgo5pe

outputs:
  prepared_dataset:
    type: uri_file
    mode: rw_mount

jobs:
  select_features:
    type: command
    component: file:../components/select_features/select-features.yml
    inputs:
      input_file: 
        path: azureml:wachttijden_raw@latest
      features: WACHTTIJD TYPE_WACHTTIJD SPECIALISME ROAZ_REGIO TYPE_ZORGINSTELLING
    outputs:
      output_file:
        type: uri_file
        mode: rw_mount
  fix_missing_values:
    type: command
    component: file:../components/fix_missing_values/fix-missing-values.yml
    inputs:
      input_file: ${{parent.jobs.select_features.outputs.output_file}}
    outputs:
      output_file: ${{parent.outputs.prepared_dataset}}
  