channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=21.2.4
  - pip:
    - interpret==0.2.7
    - azureml-core==1.43.0
    - azureml-defaults==1.43.0
    - azureml-telemetry==1.43.0
    - azureml-mlflow==1.43.0.post1
    - pandas==1.4.1
    - scikit-learn~=1.0.0
    - numpy~=1.21.0
    - scipy~=1.7.0
    - matplotlib~=3.5.0
    - psutil~=5.8.0
    - tqdm~=4.62.0